version: '3'
services:
  datapure_mysql:
    image: mysql:5.7
    container_name: datapure_mysql
    volumes:
      - datapure_mysql-volume:/data/mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=datapure-dev
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - '3307:3306'
  datapure_dev_mongo:
    image: mongo
    container_name: datapure_dev_mongo
    environment:
      - MONGO_INITDB_DATABASE=datapure
    volumes:
      - datapure-mongo-volume:/data/db
    ports:
      - '27018:27017'

  datapure_dev:
    build:
      context: .
      target: dev
    container_name: datapure_dev
    volumes:
      - ./:/app
    ports:
      - '4000:80'
    environment:
      - PORT=80
      - NODE_ENV=development
      - SQL_DATABASE_URL=mysql://user:password@datapure_mysql:3306/datapure-dev?schema=public
      - DATABASE_URL=mysql://user:password@datapure_mysql:3306/datapure-dev?schema=public
      - MONGO_DATABASE_URL=mongodb://datapure_dev_mongo:27017/datapure
      - JWT_SECRET=secretword
      - ENCRYPT_SECRET=vOVH6sdmpNWjRRIqCc7rdxs01lwHzfr3
      - GMAIL_APP_PASSWORD=eejxvfmulcaerotu
      - GMAIL_EMAIL=datapuretech@gmail.com
    restart: 'no'
    depends_on:
      - datapure_mysql

volumes:
  datapure_mysql-volume:
  datapure-mongo-volume:
