export default [
  'Aglaonema',
  'Alocasia',
  'Amydrium',
  'Anthurium',
  'Begonia',
  'Calathea',
  'Carnivorous',
  'Dieffenbachia',
  'Dracaena',
  'Edible',
  'Epiphyte',
  'Fern',
  'Ficus',
  'Hoya',
  'Hybrid Philodendron',
  'Monstera',
  'Other',
  'Peperomia',
  'Philodendron',
  'Pothos',
  'Rhaphidophora',
  'Sansevieria',
  'Scindapsus',
  'Succulent',
  'Syngonium',
  'Uncategorized'
]
